const { SlashCommandBuilder } = require('discord.js');
const { getEnv } = require('../config/env');
const supabase = require('../database/supabase');
const { writeLog } = require('../services/logs');
const data=new SlashCommandBuilder().setName('administracion').setDescription('Administración del bot')
.addSubcommand(s=>s.setName('config').setDescription('Consulta configuración').addStringOption(o=>o.setName('clave').setDescription('Clave').setRequired(true)))
.addSubcommand(s=>s.setName('set-channel').setDescription('Configura un canal').addStringOption(o=>o.setName('clave').setDescription('Clave').setRequired(true)).addChannelOption(o=>o.setName('canal').setDescription('Canal').setRequired(true)))
.addSubcommand(s=>s.setName('set-role').setDescription('Configura un rol').addStringOption(o=>o.setName('clave').setDescription('Clave').setRequired(true)).addRoleOption(o=>o.setName('rol').setDescription('Rol').setRequired(true)))
.addSubcommand(s=>s.setName('set-permission').setDescription('Configura roles de permiso').addStringOption(o=>o.setName('clave').setDescription('Permiso').setRequired(true)).addStringOption(o=>o.setName('roles').setDescription('IDs de roles separados por coma').setRequired(true)))
.addSubcommand(s=>s.setName('maintenance').setDescription('Activa o desactiva mantenimiento').addBooleanOption(o=>o.setName('activo').setDescription('Activo').setRequired(true)))
.addSubcommand(s=>s.setName('reload').setDescription('Recarga la configuración'));
async function execute(i){const allowed=['ADMINISTRATOR','DIRECTOR','FOUNDER'].some(r=>{const id=getEnv(`STAFF_ROLE_${r}_ID`)||getEnv(`OFFICIAL_ROLE_${r}_ID`);return id&&i.member.roles.cache.has(id);});if(!allowed)return i.reply({content:'No tienes permisos de administración.',ephemeral:true});const sub=i.options.getSubcommand();try{if(sub==='config'){const key=i.options.getString('clave');const {data:row}=await supabase.from('guild_config').select('config_value').eq('guild_id',i.guild.id).eq('config_key',key).maybeSingle();return i.reply({content:row?`${key}: \`${row.config_value}\``:`No existe configuración para \`${key}\`.`,ephemeral:true});}if(sub==='set-channel'||sub==='set-role'){const key=i.options.getString('clave'), value=sub==='set-channel'?i.options.getChannel('canal').id:i.options.getRole('rol').id;await supabase.from('guild_config').upsert({guild_id:i.guild.id,config_key:key,config_value:value,updated_at:new Date().toISOString()},{onConflict:'guild_id,config_key'});await writeLog({guild:i.guild,category:'administration',action:sub,actorId:i.user.id,message:`${key}=${value}`});return i.reply({content:'Configuración guardada.',ephemeral:true});}if(sub==='set-permission'){const key=i.options.getString('clave'),value=i.options.getString('roles');await supabase.from('permissions').upsert({guild_id:i.guild.id,permission_key:key,role_ids:value.split(',').map(x=>x.trim()).filter(Boolean),enabled:true,updated_at:new Date().toISOString()},{onConflict:'guild_id,permission_key'});return i.reply({content:'Permiso guardado.',ephemeral:true});}const key='maintenance';if(sub==='maintenance'){const value=String(i.options.getBoolean('activo'));await supabase.from('guild_config').upsert({guild_id:i.guild.id,config_key:key,config_value:value,updated_at:new Date().toISOString()},{onConflict:'guild_id,config_key'});await writeLog({guild:i.guild,category:'administration',action:'maintenance',actorId:i.user.id,message:value});return i.reply({content:`Mantenimiento ${value==='true'?'activado':'desactivado'}.`,ephemeral:true});}return i.reply({content:'Configuración recargada.',ephemeral:true});}catch(e){console.error(e);return i.reply({content:'No se pudo actualizar la configuración.',ephemeral:true});}}
module.exports={data,execute,guilds:['official','staff','applications']};
