const { SlashCommandBuilder, MessageFlags } = require('discord.js');
const { getEnv } = require('../config/env'); const supabase = require('../database/supabase'); const { getGuildRow } = require('../services/guilds'); const { writeLog } = require('../services/logs'); const { getGuildType } = require('../utils/guild'); const { hasConfiguredRole } = require('../utils/permissions');
const EPHEMERAL=MessageFlags.Ephemeral;
const MANAGEMENT_ROLES={official:['OFFICIAL_ROLE_FOUNDER_ID','OFFICIAL_ROLE_DIRECTOR_ID','OFFICIAL_ROLE_ADMINISTRATOR_ID'],staff:['STAFF_ROLE_FOUNDER_ID','STAFF_ROLE_DIRECTOR_ID','STAFF_ROLE_ADMINISTRATIVE_ASSISTANT_ID'],applications:['APPLICATIONS_ROLE_FOUNDER_ID','APPLICATIONS_ROLE_DIRECTOR_ID','APPLICATIONS_ROLE_ADMINISTRATOR_ID']};
const data=new SlashCommandBuilder().setName('administracion').setDescription('Administración del bot')
.addSubcommand(s=>s.setName('config').setDescription('Consulta configuración').addStringOption(o=>o.setName('clave').setDescription('Clave').setRequired(true)))
.addSubcommand(s=>s.setName('set-channel').setDescription('Configura un canal').addStringOption(o=>o.setName('clave').setDescription('Clave').setRequired(true)).addChannelOption(o=>o.setName('canal').setDescription('Canal').setRequired(true)))
.addSubcommand(s=>s.setName('set-role').setDescription('Configura un rol').addStringOption(o=>o.setName('clave').setDescription('Clave').setRequired(true)).addRoleOption(o=>o.setName('rol').setDescription('Rol').setRequired(true)))
.addSubcommand(s=>s.setName('set-permission').setDescription('Configura roles de permiso').addStringOption(o=>o.setName('clave').setDescription('Permiso').setRequired(true)).addStringOption(o=>o.setName('roles').setDescription('IDs separados por coma').setRequired(true)))
.addSubcommand(s=>s.setName('maintenance').setDescription('Mantenimiento').addBooleanOption(o=>o.setName('activo').setDescription('Activo').setRequired(true)))
.addSubcommand(s=>s.setName('reload').setDescription('Recarga configuración'));
async function execute(i){
 const type=getGuildType(i.guild.id);const allowed=type==='dev'||(MANAGEMENT_ROLES[type]||[]).some(roleEnv=>hasConfiguredRole(i.member,roleEnv));if(!allowed)return i.reply({content:'No tienes permisos de administración.',flags:EPHEMERAL});
 await i.deferReply({flags:EPHEMERAL});
 try{
  const guild=await getGuildRow(i.guild.id);if(!guild)return i.editReply({content:'Servidor no registrado.'});const sub=i.options.getSubcommand();
  if(sub==='config'){const k=i.options.getString('clave',true);const{data:r,error}=await supabase.from('guild_config').select('config_value').eq('guild_id',guild.id).eq('config_key',k).maybeSingle();if(error)throw error;return i.editReply({content:r?`${k}: \`${r.config_value}\``:`No existe \`${k}\`.`});}
  if(sub==='set-channel'||sub==='set-role'){const k=i.options.getString('clave',true),v=sub==='set-channel'?i.options.getChannel('canal',true).id:i.options.getRole('rol',true).id;const{error}=await supabase.from('guild_config').upsert({guild_id:guild.id,config_key:k,config_value:v,updated_at:new Date().toISOString()},{onConflict:'guild_id,config_key'});if(error)throw error;await writeLog({guild:i.guild,category:'administration',action:sub,actorId:i.user.id,message:`${k}=${v}`});return i.editReply({content:'Configuración guardada.'});}
  if(sub==='set-permission'){const k=i.options.getString('clave',true),v=i.options.getString('roles',true).split(',').map(x=>x.trim()).filter(Boolean);const{error}=await supabase.from('permissions').upsert({guild_id:guild.id,permission_key:k,role_ids:v,enabled:true,updated_at:new Date().toISOString()},{onConflict:'guild_id,permission_key'});if(error)throw error;return i.editReply({content:'Permiso guardado.'});}
  if(sub==='maintenance'){const v=String(i.options.getBoolean('activo',true));const{error}=await supabase.from('guild_config').upsert({guild_id:guild.id,config_key:'maintenance',config_value:v,updated_at:new Date().toISOString()},{onConflict:'guild_id,config_key'});if(error)throw error;await writeLog({guild:i.guild,category:'administration',action:'maintenance',actorId:i.user.id,message:v});return i.editReply({content:`Mantenimiento ${v==='true'?'activado':'desactivado'}.`});}
  return i.editReply({content:'Configuración recargada.'});
 }catch(e){console.error('[HYPNOX] Administration error:',e);return i.editReply({content:'No se pudo actualizar la configuración.'}).catch(()=>{});}
}
module.exports={data,execute,guilds:['official','staff','applications'],access:{roleEnvs:['OFFICIAL_ROLE_FOUNDER_ID','OFFICIAL_ROLE_DIRECTOR_ID','OFFICIAL_ROLE_ADMINISTRATOR_ID','STAFF_ROLE_FOUNDER_ID','STAFF_ROLE_DIRECTOR_ID','STAFF_ROLE_ADMINISTRATIVE_ASSISTANT_ID','APPLICATIONS_ROLE_FOUNDER_ID','APPLICATIONS_ROLE_DIRECTOR_ID','APPLICATIONS_ROLE_ADMINISTRATOR_ID']}};
