const { SlashCommandBuilder, MessageFlags } = require('discord.js');
const supabase = require('../database/supabase');
const { writeLog } = require('../services/logs');
const { getEnv } = require('../config/env');
const { getGuildRow } = require('../services/guilds');
const { getGuildType } = require('../utils/guild');
const { brandedEmbed, addSection } = require('../utils/embeds');
const EPHEMERAL=MessageFlags.Ephemeral;
const TYPES={anuncio:{label:'ANUNCIO OFICIAL',description:'Comunicación institucional de Hypnox Studios para informar a la comunidad.'},actividad:{label:'ACTIVIDAD',description:'Actividad organizada por Hypnox Studios para fomentar la participación de la comunidad.'},dinamica:{label:'DINÁMICA',description:'Dinámica de participación creada para la comunidad de Hypnox Studios.'},evento:{label:'EVENTO',description:'Información oficial relacionada con un evento de Hypnox Studios.'},serie:{label:'SERIE',description:'Actualización oficial sobre una serie o producción de Hypnox Studios.'},episodio:{label:'EPISODIO',description:'Publicación correspondiente a un nuevo episodio o entrega de una serie.'}};
const DB_ANNOUNCEMENT_TYPES={anuncio:'official',actividad:'activity',dinamica:'dynamic',evento:'event',serie:'series',episodio:'episode'};
const STAFF_ROLES=['OFFICIAL_ROLE_FOUNDER_ID','OFFICIAL_ROLE_DIRECTOR_ID','OFFICIAL_ROLE_ADMINISTRATOR_ID','OFFICIAL_ROLE_SRMOD_ID','OFFICIAL_ROLE_MOD_ID','OFFICIAL_ROLE_TMOD_ID','OFFICIAL_ROLE_HELPER_ID','OFFICIAL_ROLE_DEVELOPER_ID','OFFICIAL_ROLE_PRODUCER_ID','STAFF_ROLE_FOUNDER_ID','STAFF_ROLE_DIRECTOR_ID','STAFF_ROLE_ADMINISTRATIVE_ASSISTANT_ID','STAFF_ROLE_SRMOD_ID','STAFF_ROLE_MOD_ID','STAFF_ROLE_TMOD_ID','STAFF_ROLE_HELPER_ID','STAFF_ROLE_PROJECT_MANAGER_ID','STAFF_ROLE_DEPARTMENT_LEAD_ID'];
const data=new SlashCommandBuilder().setName('anuncio').setDescription('Publica una comunicación oficial de Hypnox Studios.').addStringOption(o=>o.setName('tipo').setDescription('Clasificación de la publicación.').setRequired(true).addChoices(...Object.entries(TYPES).map(([value,c])=>({name:c.label,value})))).addStringOption(o=>o.setName('titulo').setDescription('Título principal.').setMinLength(1).setMaxLength(180).setRequired(true)).addStringOption(o=>o.setName('contenido').setDescription('Contenido principal.').setMinLength(1).setMaxLength(3800).setRequired(true)).addStringOption(o=>o.setName('imagen').setDescription('URL de imagen.').setMaxLength(1000));
async function getAnnouncementChannel(i){const t=getGuildType(i.guild.id),key=t==='official'?'OFFICIAL_CHANNEL_ANNOUNCEMENTS_ID':'STAFF_CHANNEL_ANNOUNCEMENTS_ID',id=getEnv(key);if(!id)return{channel:t==='staff'&&i.channel?.isTextBased()?i.channel:null,envKey:key};const c=await i.guild.channels.fetch(id).catch(()=>null);return{channel:c?.isTextBased()?c:null,envKey:key}}
async function execute(i){await i.deferReply({flags:EPHEMERAL});try{const guild=await getGuildRow(i.guild.id);if(!guild)return i.editReply({content:'El servidor aún no está registrado en Supabase.'});const type=i.options.getString('tipo',true),title=i.options.getString('titulo',true).trim(),content=i.options.getString('contenido',true).trim(),gt=getGuildType(i.guild.id),supplied=i.options.getString('imagen')?.trim(),image=supplied||(gt==='official'?getEnv('OFFICIAL_IMAGE_ANNOUNCEMENT')||getEnv('OFFICIAL_IMAGE_BANNER'):getEnv('STAFF_IMAGE_ANNOUNCEMENT')||getEnv('STAFF_IMAGE_BANNER')),config=TYPES[type],dbType=DB_ANNOUNCEMENT_TYPES[type];if(!config)return i.editReply({content:'El tipo de anuncio no es válido.'});const {channel,envKey}=await getAnnouncementChannel(i);if(!channel)return i.editReply({content:`Configura ${envKey} en el entorno del bot antes de publicar anuncios.`});const e=brandedEmbed(title,content,{image,footerText:`Hypnox Studios • ${config.label}`});addSection(e,'Clasificación',`**${config.label}**\n${config.description}`);let message;try{message=await channel.send({embeds:[e]});const{error}=await supabase.from('announcements').insert({guild_id:guild.id,channel_id:channel.id,message_id:message.id,announcement_type:dbType,title,content,image_url:image||null,author_discord_user_id:i.user.id});if(error)throw error;await writeLog({guild:i.guild,category:'system',action:type,actorId:i.user.id,channelId:channel.id,message:title});}catch(error){if(message)await message.delete().catch(()=>{});throw error}return i.editReply({content:`Publicación enviada en <#${channel.id}>.`})}catch(error){console.error('[HYPNOX] Announcement error:',error);return i.editReply({content:'No se pudo publicar el anuncio. El error fue registrado.'}).catch(()=>{})}}
module.exports={data,execute,guilds:['official','staff'],access:{roleEnvs:STAFF_ROLES}};
