const { SlashCommandBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, PermissionFlagsBits, MessageFlags } = require('discord.js');
const supabase = require('../database/supabase');
const { getGuildRow } = require('../services/guilds');
const { brandedEmbed } = require('../utils/embeds');
const { writeLog } = require('../services/logs');
const data=new SlashCommandBuilder().setName('encuesta').setDescription('Crea y administra encuestas.')
 .addSubcommand(s=>s.setName('crear').setDescription('Crea una encuesta.').addStringOption(o=>o.setName('pregunta').setDescription('Pregunta.').setMaxLength(300).setRequired(true)).addStringOption(o=>o.setName('opciones').setDescription('Opciones separadas por | (2 a 5).').setMaxLength(500).setRequired(true)))
 .addSubcommand(s=>s.setName('cerrar').setDescription('Cierra una encuesta.').addStringOption(o=>o.setName('id').setDescription('ID de encuesta.').setRequired(true)));
function embed(poll){const votes=poll.votes||{};const opts=Array.isArray(poll.options)?poll.options:[];const total=Object.values(votes).reduce((a,v)=>a+Number(v||0),0);return brandedEmbed('ENCUESTA',poll.question,{footerText:`Hypnox Studios • ${total} voto${total===1?'':'s'}`,fields:opts.map((x,i)=>({name:`◆ ${i+1}. ${x}`,value:`**${Number(votes[i]||0)}** voto${Number(votes[i]||0)===1?'':'s'}`,inline:true}))});}
function row(poll){return new ActionRowBuilder().addComponents(poll.options.map((x,i)=>new ButtonBuilder().setCustomId(`poll:${poll.id}:${i}`).setLabel(String(x).slice(0,80)).setStyle(ButtonStyle.Secondary)));}
async function execute(i){const sub=i.options.getSubcommand();if(!i.memberPermissions?.has(PermissionFlagsBits.ManageGuild)&&sub==='cerrar')return i.reply({content:'Se requiere gestionar el servidor.',flags:MessageFlags.Ephemeral});await i.deferReply({flags:MessageFlags.Ephemeral});try{const g=await getGuildRow(i.guildId);if(!g)return i.editReply({content:'El servidor no está registrado.'});if(sub==='crear'){const opts=i.options.getString('opciones',true).split('|').map(x=>x.trim()).filter(Boolean);const q=i.options.getString('pregunta',true).trim();if(opts.length<2||opts.length>5)return i.editReply({content:'La encuesta debe tener entre 2 y 5 opciones separadas por |.'});const {data:p,error}=await supabase.from('polls').insert({guild_id:g.id,channel_id:i.channelId,question:q,options:opts,votes:{},created_by_discord_user_id:i.user.id}).select().single();if(error)throw error;const msg=await i.channel.send({embeds:[embed(p)],components:[row(p)]});await supabase.from('polls').update({message_id:msg.id}).eq('id',p.id);await writeLog({guild:i.guild,category:'system',action:'encuesta_creada',actorId:i.user.id,channelId:i.channelId,message:q,metadata:{pollId:p.id}});return i.editReply({content:`Encuesta creada. ID: \`${p.id}\`.`});}const id=i.options.getString('id',true);const {data:p,error}=await supabase.from('polls').select('*').eq('guild_id',g.id).eq('id',id).maybeSingle();if(error)throw error;if(!p)return i.editReply({content:'No se encontró la encuesta.'});if(p.status==='closed')return i.editReply({content:'La encuesta ya está cerrada.'});await supabase.from('polls').update({status:'closed',closed_at:new Date().toISOString()}).eq('id',id);const ch=await i.guild.channels.fetch(p.channel_id).catch(()=>null);if(ch?.isTextBased()&&p.message_id){const m=await ch.messages.fetch(p.message_id).catch(()=>null);if(m)await m.edit({embeds:[embed(p)],components:[]}).catch(()=>{});}return i.editReply({content:`Encuesta \`${id}\` cerrada.`});}catch(e){console.error('[HYPNOX] Encuesta:',e);return i.editReply({content:'No se pudo procesar la encuesta.'}).catch(()=>{});}}
module.exports={data,execute,guilds:['official','staff']};
