const { SlashCommandBuilder, PermissionFlagsBits } = require('discord.js');
const { getEnv } = require('../config/env');
const { createApplication, activeApplication, updateApplication, createInterview } = require('../services/applications');
const { writeLog } = require('../services/logs');
const data=new SlashCommandBuilder().setName('postulacion').setDescription('Sistema de postulaciones Staff')
.addSubcommand(s=>s.setName('postular').setDescription('Inicia una postulación').addStringOption(o=>o.setName('informacion').setDescription('Información adicional').setRequired(false)))
.addSubcommand(s=>s.setName('estado').setDescription('Consulta tu estado'))
.addSubcommand(s=>s.setName('revisar').setDescription('Revisa una postulación').addStringOption(o=>o.setName('id').setDescription('ID').setRequired(true)).addStringOption(o=>o.setName('resultado').setDescription('Resultado').setRequired(true).addChoices({name:'Aprobada',value:'approved'},{name:'Rechazada',value:'rejected'})).addStringOption(o=>o.setName('notas').setDescription('Notas')))
.addSubcommand(s=>s.setName('entrevista').setDescription('Programa entrevista').addStringOption(o=>o.setName('id').setDescription('ID').setRequired(true)).addStringOption(o=>o.setName('fecha').setDescription('Fecha ISO').setRequired(true)))
.addSubcommand(s=>s.setName('resultado-entrevista').setDescription('Registra resultado oral').addStringOption(o=>o.setName('id').setDescription('ID').setRequired(true)).addStringOption(o=>o.setName('resultado').setDescription('Resultado').setRequired(true).addChoices({name:'Aprobada',value:'approved'},{name:'Rechazada',value:'rejected'})).addStringOption(o=>o.setName('notas').setDescription('Notas')));
async function execute(i){const sub=i.options.getSubcommand();try{if(sub==='postular'){const row=await createApplication(i.guild.id,i.user.id,{info:i.options.getString('informacion')||''});if(row.cooldown)return i.reply({content:`Puedes volver a postular desde <t:${Math.floor(new Date(row.cooldown).getTime()/1000)}:R>.`,ephemeral:true});const url=getEnv('APPLICATION_FORM_URL');await writeLog({guild:i.guild,category:'application',action:'submit',actorId:i.user.id,message:row.id});return i.reply({content:`Postulación iniciada. Completa el formulario de Fase 1${url?` aquí: ${url}`:'. El enlace del formulario aún debe configurarse.'}\nID: \`${row.id}\``,ephemeral:true});}if(sub==='estado'){const row=await activeApplication(i.guild.id,i.user.id);return i.reply({content:row?`Estado: **${row.status}** · Fase: **${row.phase}** · ID: \`${row.id}\``:'No tienes una postulación registrada.',ephemeral:true});}if(!i.member.permissions.has(PermissionFlagsBits.ManageGuild))return i.reply({content:'No tienes permisos.',ephemeral:true});const id=i.options.getString('id');if(sub==='revisar'){const result=i.options.getString('resultado');const cooldown=result==='rejected'?new Date(Date.now()+86400000).toISOString():null;await updateApplication(id,{status:result==='approved'?'phase2':'rejected',phase:result==='approved'?2:1,reviewer_discord_user_id:i.user.id,reviewed_at:new Date().toISOString(),cooldown_until:cooldown});await writeLog({guild:i.guild,category:'application',action:'review',actorId:i.user.id,message:id,metadata:{result}});return i.reply({content:'Postulación revisada.',ephemeral:true});}if(sub==='entrevista'){const date=new Date(i.options.getString('fecha'));if(Number.isNaN(date.getTime()))return i.reply({content:'Fecha ISO inválida.',ephemeral:true});const interview=await createInterview(id,i.user.id,date.toISOString());await updateApplication(id,{phase:2,status:'interview_scheduled'});await writeLog({guild:i.guild,category:'application',action:'interview_scheduled',actorId:i.user.id,message:id});return i.reply({content:`Entrevista programada: \`${interview.id}\`.`,ephemeral:true});}const result=i.options.getString('resultado');await updateApplication(id,{status:result==='approved'?'approved':'rejected',phase:2,cooldown_until:result==='rejected'?new Date(Date.now()+86400000).toISOString():null});await writeLog({guild:i.guild,category:'application',action:'interview_result',actorId:i.user.id,message:i.options.getString('notas')||id,metadata:{applicationId:id,result}});return i.reply({content:'Resultado de entrevista registrado.',ephemeral:true});}catch(e){console.error(e);return i.reply({content:'No se pudo gestionar la postulación.',ephemeral:true});}}
module.exports={data,execute,guilds:['applications']};
