const { SlashCommandBuilder } = require('discord.js');
const supabase = require('../database/supabase');
const { getGuildRow } = require('../services/guilds');
const { writeLog } = require('../services/logs');
const PROJECT_ROLES=['STAFF_ROLE_FOUNDER_ID','STAFF_ROLE_DIRECTOR_ID','STAFF_ROLE_ADMINISTRATOR_ID','STAFF_ROLE_PROJECT_MANAGER_ID','STAFF_ROLE_DEPARTMENT_LEAD_ID'];
const data=new SlashCommandBuilder().setName('proyecto').setDescription('Gestiona proyectos internos')
.addSubcommand(s=>s.setName('crear').setDescription('Crea un proyecto').addStringOption(o=>o.setName('nombre').setDescription('Nombre').setRequired(true)).addStringOption(o=>o.setName('descripcion').setDescription('Descripción')))
.addSubcommand(s=>s.setName('editar').setDescription('Edita un proyecto').addStringOption(o=>o.setName('id').setDescription('ID').setRequired(true)).addStringOption(o=>o.setName('nombre').setDescription('Nombre')).addStringOption(o=>o.setName('descripcion').setDescription('Descripción')).addStringOption(o=>o.setName('estado').setDescription('Estado')))
.addSubcommand(s=>s.setName('estado').setDescription('Consulta un proyecto').addStringOption(o=>o.setName('id').setDescription('ID').setRequired(true)))
.addSubcommand(s=>s.setName('cerrar').setDescription('Cierra un proyecto').addStringOption(o=>o.setName('id').setDescription('ID').setRequired(true)))
.addSubcommand(s=>s.setName('asignar').setDescription('Asigna manager').addStringOption(o=>o.setName('id').setDescription('ID').setRequired(true)).addUserOption(o=>o.setName('usuario').setDescription('Manager').setRequired(true)));
async function execute(i){const guild=await getGuildRow(i.guild.id);if(!guild)return i.reply({content:'Servidor no registrado.',ephemeral:true});try{const sub=i.options.getSubcommand();if(sub==='crear'){const {data:p,error}=await supabase.from('projects').insert({guild_id:guild.id,name:i.options.getString('nombre'),description:i.options.getString('descripcion'),created_by_discord_user_id:i.user.id}).select().single();if(error)throw error;await writeLog({guild:i.guild,category:'project',action:'create',actorId:i.user.id,message:p.name,metadata:{projectId:p.id}});return i.reply({content:`Proyecto creado: \`${p.id}\``,ephemeral:true});}const id=i.options.getString('id');let patch={updated_at:new Date().toISOString()};if(sub==='editar'){if(i.options.getString('nombre'))patch.name=i.options.getString('nombre');if(i.options.getString('descripcion'))patch.description=i.options.getString('descripcion');if(i.options.getString('estado'))patch.status=i.options.getString('estado');}if(sub==='cerrar')patch.status='closed';if(sub==='asignar')patch.manager_discord_user_id=i.options.getUser('usuario').id;if(sub==='estado'){const {data:p,error}=await supabase.from('projects').select('*').eq('id',id).eq('guild_id',guild.id).maybeSingle();if(error)throw error;return i.reply({content:p?`**${p.name}**\nEstado: **${p.status}**\nManager: ${p.manager_discord_user_id?`<@${p.manager_discord_user_id}>`:'Sin asignar'}\nID: \`${p.id}\``:'Proyecto no encontrado.',ephemeral:true});}const {data:p,error}=await supabase.from('projects').update(patch).eq('id',id).eq('guild_id',guild.id).select().single();if(error)throw error;await writeLog({guild:i.guild,category:'project',action:sub,actorId:i.user.id,message:id});return i.reply({content:`Proyecto actualizado: ${p.name}.`,ephemeral:true});}catch(e){console.error(e);return i.reply({content:'No se pudo gestionar el proyecto.',ephemeral:true});}}
module.exports={data,execute,guilds:['staff'],access:{roleEnvs:PROJECT_ROLES}};
