const { getEnv } = require('../config/env');

const LEVELS = {
  helper: {
    official: ['OFFICIAL_ROLE_HELPER_ID', 'OFFICIAL_ROLE_TMOD_ID', 'OFFICIAL_ROLE_MOD_ID', 'OFFICIAL_ROLE_SRMOD_ID', 'OFFICIAL_ROLE_ADMINISTRATOR_ID', 'OFFICIAL_ROLE_DIRECTOR_ID', 'OFFICIAL_ROLE_FOUNDER_ID'],
    staff: ['STAFF_ROLE_HELPER_ID', 'STAFF_ROLE_TMOD_ID', 'STAFF_ROLE_MOD_ID', 'STAFF_ROLE_SRMOD_ID', 'STAFF_ROLE_ADMINISTRATIVE_ASSISTANT_ID', 'STAFF_ROLE_DIRECTOR_ID', 'STAFF_ROLE_FOUNDER_ID']
  },
  tmod: {
    official: ['OFFICIAL_ROLE_TMOD_ID', 'OFFICIAL_ROLE_MOD_ID', 'OFFICIAL_ROLE_SRMOD_ID', 'OFFICIAL_ROLE_ADMINISTRATOR_ID', 'OFFICIAL_ROLE_DIRECTOR_ID', 'OFFICIAL_ROLE_FOUNDER_ID'],
    staff: ['STAFF_ROLE_TMOD_ID', 'STAFF_ROLE_MOD_ID', 'STAFF_ROLE_SRMOD_ID', 'STAFF_ROLE_ADMINISTRATIVE_ASSISTANT_ID', 'STAFF_ROLE_DIRECTOR_ID', 'STAFF_ROLE_FOUNDER_ID']
  },
  mod: {
    official: ['OFFICIAL_ROLE_MOD_ID', 'OFFICIAL_ROLE_SRMOD_ID', 'OFFICIAL_ROLE_ADMINISTRATOR_ID', 'OFFICIAL_ROLE_DIRECTOR_ID', 'OFFICIAL_ROLE_FOUNDER_ID'],
    staff: ['STAFF_ROLE_MOD_ID', 'STAFF_ROLE_SRMOD_ID', 'STAFF_ROLE_ADMINISTRATIVE_ASSISTANT_ID', 'STAFF_ROLE_DIRECTOR_ID', 'STAFF_ROLE_FOUNDER_ID']
  },
  srmod: {
    official: ['OFFICIAL_ROLE_SRMOD_ID', 'OFFICIAL_ROLE_ADMINISTRATOR_ID', 'OFFICIAL_ROLE_DIRECTOR_ID', 'OFFICIAL_ROLE_FOUNDER_ID'],
    staff: ['STAFF_ROLE_SRMOD_ID', 'STAFF_ROLE_ADMINISTRATIVE_ASSISTANT_ID', 'STAFF_ROLE_DIRECTOR_ID', 'STAFF_ROLE_FOUNDER_ID']
  },
  management: {
    official: ['OFFICIAL_ROLE_ADMINISTRATOR_ID', 'OFFICIAL_ROLE_DIRECTOR_ID', 'OFFICIAL_ROLE_FOUNDER_ID'],
    staff: ['STAFF_ROLE_ADMINISTRATIVE_ASSISTANT_ID', 'STAFF_ROLE_DIRECTOR_ID', 'STAFF_ROLE_FOUNDER_ID'],
    applications: ['APPLICATIONS_ROLE_ADMINISTRATOR_ID', 'APPLICATIONS_ROLE_DIRECTOR_ID', 'APPLICATIONS_ROLE_FOUNDER_ID']
  },
  announcements: {
    official: ['OFFICIAL_ROLE_HELPER_ID', 'OFFICIAL_ROLE_TMOD_ID', 'OFFICIAL_ROLE_MOD_ID', 'OFFICIAL_ROLE_SRMOD_ID', 'OFFICIAL_ROLE_ADMINISTRATOR_ID', 'OFFICIAL_ROLE_DIRECTOR_ID', 'OFFICIAL_ROLE_FOUNDER_ID'],
    staff: ['STAFF_ROLE_PROJECT_MANAGER_ID', 'STAFF_ROLE_DEPARTMENT_LEAD_ID', 'STAFF_ROLE_ADMINISTRATIVE_ASSISTANT_ID', 'STAFF_ROLE_DIRECTOR_ID', 'STAFF_ROLE_FOUNDER_ID']
  },
  administration: {
    official: ['OFFICIAL_ROLE_ADMINISTRATOR_ID', 'OFFICIAL_ROLE_DIRECTOR_ID', 'OFFICIAL_ROLE_FOUNDER_ID'],
    staff: ['STAFF_ROLE_ADMINISTRATIVE_ASSISTANT_ID', 'STAFF_ROLE_DIRECTOR_ID', 'STAFF_ROLE_FOUNDER_ID'],
    applications: ['APPLICATIONS_ROLE_ADMINISTRATOR_ID', 'APPLICATIONS_ROLE_DIRECTOR_ID', 'APPLICATIONS_ROLE_FOUNDER_ID']
  }
};

function hasRole(member, guildType, roleEnv) {
  const id = getEnv(roleEnv);
  return Boolean(id && member?.roles?.cache?.has(id));
}

function hasLevel(member, guildType, level) {
  return (LEVELS[level]?.[guildType] || []).some((roleEnv) => hasRole(member, guildType, roleEnv));
}

function isStaff(member, guildType) {
  return hasLevel(member, guildType, 'helper');
}

module.exports = { hasRole, hasLevel, isStaff, LEVELS };
