const { hasConfiguredRole } = require('./permissions');
const { getGuildType } = require('./guild');

const STAFF_OFFICIAL = ['OFFICIAL_ROLE_FOUNDER_ID', 'OFFICIAL_ROLE_DIRECTOR_ID', 'OFFICIAL_ROLE_ADMINISTRATOR_ID', 'OFFICIAL_ROLE_SRMOD_ID', 'OFFICIAL_ROLE_MOD_ID', 'OFFICIAL_ROLE_TMOD_ID', 'OFFICIAL_ROLE_HELPER_ID'];
const STAFF_TEAM = ['STAFF_ROLE_FOUNDER_ID', 'STAFF_ROLE_DIRECTOR_ID', 'STAFF_ROLE_ADMINISTRATOR_ID', 'STAFF_ROLE_ADMINISTRATIVE_ASSISTANT_ID', 'STAFF_ROLE_SRMOD_ID', 'STAFF_ROLE_MOD_ID', 'STAFF_ROLE_TMOD_ID', 'STAFF_ROLE_HELPER_ID', 'STAFF_ROLE_PROJECT_MANAGER_ID', 'STAFF_ROLE_DEPARTMENT_LEAD_ID'];
const MANAGEMENT_OFFICIAL = ['OFFICIAL_ROLE_FOUNDER_ID', 'OFFICIAL_ROLE_DIRECTOR_ID', 'OFFICIAL_ROLE_ADMINISTRATOR_ID'];
const MANAGEMENT_STAFF = ['STAFF_ROLE_FOUNDER_ID', 'STAFF_ROLE_DIRECTOR_ID', 'STAFF_ROLE_ADMINISTRATOR_ID'];
const APPLICATION_STAFF = ['APPLICATIONS_ROLE_FOUNDER_ID', 'APPLICATIONS_ROLE_DIRECTOR_ID', 'APPLICATIONS_ROLE_ADMINISTRATOR_ID', 'APPLICATIONS_ROLE_APPLICATION_MANAGER_ID', 'APPLICATIONS_ROLE_APPLICATION_REVIEWER_ID'];
const PROJECT_STAFF = ['STAFF_ROLE_FOUNDER_ID', 'STAFF_ROLE_DIRECTOR_ID', 'STAFF_ROLE_ADMINISTRATOR_ID', 'STAFF_ROLE_PROJECT_MANAGER_ID', 'STAFF_ROLE_DEPARTMENT_LEAD_ID'];

const CATEGORY_PERMISSIONS = {
  informacion: { official: ['OFFICIAL_ROLE_MEMBER_ID'], staff: STAFF_TEAM, applications: APPLICATION_STAFF },
  comunidad: { official: ['OFFICIAL_ROLE_MEMBER_ID'] },
  moderacion: { official: STAFF_OFFICIAL, staff: STAFF_TEAM },
  tickets: { official: STAFF_OFFICIAL },
  anuncios: { official: STAFF_OFFICIAL, staff: STAFF_TEAM },
  eventos: { official: STAFF_OFFICIAL, staff: STAFF_TEAM },
  premios: { official: MANAGEMENT_OFFICIAL, staff: MANAGEMENT_STAFF },
  postulaciones: { official: ['OFFICIAL_ROLE_FOUNDER_ID', 'OFFICIAL_ROLE_DIRECTOR_ID', 'OFFICIAL_ROLE_ADMINISTRATOR_ID', 'OFFICIAL_ROLE_SRMOD_ID'] },
  proyectos: { staff: PROJECT_STAFF },
  administracion: { official: MANAGEMENT_OFFICIAL, staff: MANAGEMENT_STAFF, applications: ['APPLICATIONS_ROLE_FOUNDER_ID', 'APPLICATIONS_ROLE_DIRECTOR_ID', 'APPLICATIONS_ROLE_ADMINISTRATOR_ID'] }
};

function canViewHelpCategory(member, category) {
  if (getGuildType(member?.guild?.id) === 'dev') return true;
  const roles = CATEGORY_PERMISSIONS[category]?.[getGuildType(member?.guild?.id)] || [];
  return roles.some((roleEnv) => hasConfiguredRole(member, roleEnv));
}

module.exports = { CATEGORY_PERMISSIONS, canViewHelpCategory };
